### ISSUE TITLE
Problem restoring Hades Q3 lockfile

### ISSUE THREAD

**Issue by ablack3** [OHDSI/Hades#28]
I get the following error when running renv restore.
<img width="618" alt="image" src="https://github.com/OHDSI/Hades/assets/10227522/4394be10-a31c-4344-8c17-77cdf0d3499e">

The hades Q3 release requires Matrix 1.5-3
https://github.com/OHDSI/Hades/blob/69f0db8a49d3c90ce297059de6cb0e9381130ff3/hadesWideReleases/2023Q3/renv.lock#L426

and requires MatrixModels 0.5-2

https://github.com/OHDSI/Hades/blob/69f0db8a49d3c90ce297059de6cb0e9381130ff3/hadesWideReleases/2023Q3/renv.lock#L1128

But MatrixModels 0.5-2 requires Matrix 1.6 or later

Here is description file which I downloaded from [here](https://github.com/cran/MatrixModels/releases/tag/0.5-2):
<img width="638" alt="image" src="https://github.com/OHDSI/Hades/assets/10227522/467f98c2-1725-4c3f-bc99-10930905d626">

So there is an inconsistency in this lockfile, right?

@anthonysena, @konstjar

**Comment by ablack3** [comment]
I modified the lockfile manually to require Matrix 1.6-0 and `renv::restore` worked. 👍

**Comment by schuemie** [comment]
Thanks @ablack3 ! 

That is really weird. I of course based the lock file on an existing library, and tested rebuilding the lock file and did not see that error. I went back to the machine I used at the time, and the MatrixModels DESCRIPTION does list the same requirement for Matrix. I'm not sure what changed since then. The only thing I can come up with is that the parsing of package version numbers was updated (and Matrix uses a weird version numbering).

I'll make the change in the Q3 lock file itself. It should not affect any analytics, and just helps build the library. For bigger changes I think we'll introduce patch releases
